language: go

go:
  - 1.13.x

git:
  depth: 1

install:
  - git clone https://github.com/gohugoio/hugo.git
  - cd hugo
  - git checkout v0.69.2
  - git submodule init &&  git submodule update
  - go install --tags extended
  - cd ..

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  # token is set in travis-ci.org dashboard
  github_token: $GITHUB_API_KEY
  on:
    branch: hugo
  local_dir: public
  repo: shadow1163/shadow1163.github.io
  target_branch: master
  email: deploy@travis-ci.org
  name: deployment-bot
