baseURL = "http://shadow1163.github.io/"
languageCode = "en-us"
title = "Shadow1163's Blog"
theme = "capsule"
canonifyURLs = true
SectionPagesMenu = "main"

[params]
  share = true
  searchURL = "https://bing.com"
  related = "all"
